# Generated by Django 5.1.3 on 2024-11-18 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.CharField(max_length=128)),
                ("json_web_token", models.CharField(max_length=1024)),
            ],
            options={
                "db_table": "users",
            },
        ),
    ]
